package com.mutuChat.wolfkill.utils;

public class CommonUtils {
	public static String SUCCESS = "success";
	public final static String LINE = "-";
    public final static String UNIQUE_ID="uniqueId";
    public final static String MATCH_NUM = "matchNum";
    public final static String ROLE_NAME="roleName";
    public final static String ZERO="0";
    public final static String ONE="1";
	public final static String PROPHET = "prophet";
	public final static String WITCH = "witch";
	public final static String HUNTER = "hunter";
	public final static String IDIOT = "idiot";
	public final static String SILENT = "silent";
	public final static String GUARD = "guard";
	public final static String WALKER = "walker";
	public final static String WHITEWOLF = "whitewolf";
	public final static String BEAUTYWOLF = "beautywolf";
	public final static String WOLF = "wolf";
	public final static String CUPID = "cupid";
	public final static String VILLAGER = "villager";
	public final static String KNIGHT = "knight";
	public final static String DEVIL ="devil";
	public final static String THIFE ="thife";
	public final static String WOLFBOY ="wolfboy";
	public final static String BEAR ="bear";
	public final static String QTZL = "青铜战狼";
	public final static String BYZL = "白银战狼";
	public final static String HJZL = "黄金战狼";
	public final static String BJZL = "白金战狼";
	public final static String ZSZL = "钻石战狼";
	public final static String PEOTEAM = "好人阵营";
	public final static String WOLFTEAM = "狼人阵营";
	public final static String OTHERTEAM = "其他阵营";
	public final static int BYLV = 1500;
	public final static int HJLV = 3000;
	public final static int BJLV = 4500;
	public final static int ZSLV = 6000;
	public final static int PEOADD = 50;
	public final static int GODADD1 = 60;
	public final static int GODADD2 = 70;
	public final static int WOLADD = 80;
	public final static int OTHERADD = 100;
	public final static int MVPADD = 20;
}
