package com.mutuChat.wolfkill.model;

// Generated 2017-4-28 16:49:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MutuAccountInfo generated by hbm2java
 */
@Entity
@Table(name = "mutu_account_info")
public class MutuAccountInfo implements java.io.Serializable {

 
    private static final long serialVersionUID = -2000186857209567950L;
    private int uid;
    private String accName;
    private String accPass;

    public MutuAccountInfo() {
    }

    public MutuAccountInfo(String accName, String accPass) {
        this.accName = accName;
        this.accPass = accPass;
    }

    @Id
    @Column(name = "UID", unique = true, nullable = false)
    public Integer getUid() {
        return this.uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    @Column(name = "ACC_NAME", length = 30)
    public String getAccName() {
        return this.accName;
    }

    public void setAccName(String accName) {
        this.accName = accName;
    }

    @Column(name = "ACC_PASS", length = 20)
    public String getAccPass() {
        return this.accPass;
    }

    public void setAccPass(String accPass) {
        this.accPass = accPass;
    }

}
