package com.test.wolfkill.model;

// Generated 2017-6-28 15:23:52 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WolfKillMainInfoHistory generated by hbm2java
 */
@Entity
@Table(name = "wolf_kill_main_info_history")
public class WolfKillMainInfoHistory implements java.io.Serializable {

  
    private static final long serialVersionUID = -7796183170333355828L;
    private Integer id;
    private String playerName;
    private String uniqueId;
    private Integer peoNum;
    private Integer peoWon;
    private Integer wolfNum;
    private Integer wolfWon;
    private Integer otherNum;
    private Integer otherWon;
    private Integer mvp;
    private Integer levelNum;
    private String level;
    private Integer levelMaxNum;
    private Integer achiveNum;
    private Integer matchNum;

    public WolfKillMainInfoHistory() {
    }

    public WolfKillMainInfoHistory(String playerName, String uniqueId) {
        this.playerName = playerName;
        this.uniqueId = uniqueId;
    }

    public WolfKillMainInfoHistory(String playerName, String uniqueId, Integer peoNum, Integer peoWon, Integer wolfNum,
            Integer wolfWon, Integer otherNum, Integer otherWon, Integer mvp, Integer levelNum, String level,
            Integer levelMaxNum, Integer achiveNum, Integer matchNum) {
        this.playerName = playerName;
        this.uniqueId = uniqueId;
        this.peoNum = peoNum;
        this.peoWon = peoWon;
        this.wolfNum = wolfNum;
        this.wolfWon = wolfWon;
        this.otherNum = otherNum;
        this.otherWon = otherWon;
        this.mvp = mvp;
        this.levelNum = levelNum;
        this.level = level;
        this.levelMaxNum = levelMaxNum;
        this.achiveNum = achiveNum;
        this.matchNum = matchNum;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "PLAYER_NAME", nullable = false, length = 100)
    public String getPlayerName() {
        return this.playerName;
    }

    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    @Column(name = "UNIQUE_ID", nullable = false, length = 20)
    public String getUniqueId() {
        return this.uniqueId;
    }

    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    @Column(name = "PEO_NUM")
    public Integer getPeoNum() {
        return this.peoNum;
    }

    public void setPeoNum(Integer peoNum) {
        this.peoNum = peoNum;
    }

    @Column(name = "PEO_WON")
    public Integer getPeoWon() {
        return this.peoWon;
    }

    public void setPeoWon(Integer peoWon) {
        this.peoWon = peoWon;
    }

    @Column(name = "WOLF_NUM")
    public Integer getWolfNum() {
        return this.wolfNum;
    }

    public void setWolfNum(Integer wolfNum) {
        this.wolfNum = wolfNum;
    }

    @Column(name = "WOLF_WON")
    public Integer getWolfWon() {
        return this.wolfWon;
    }

    public void setWolfWon(Integer wolfWon) {
        this.wolfWon = wolfWon;
    }

    @Column(name = "OTHER_NUM")
    public Integer getOtherNum() {
        return this.otherNum;
    }

    public void setOtherNum(Integer otherNum) {
        this.otherNum = otherNum;
    }

    @Column(name = "OTHER_WON")
    public Integer getOtherWon() {
        return this.otherWon;
    }

    public void setOtherWon(Integer otherWon) {
        this.otherWon = otherWon;
    }

    @Column(name = "MVP")
    public Integer getMvp() {
        return this.mvp;
    }

    public void setMvp(Integer mvp) {
        this.mvp = mvp;
    }

    @Column(name = "LEVEL_NUM")
    public Integer getLevelNum() {
        return this.levelNum;
    }

    public void setLevelNum(Integer levelNum) {
        this.levelNum = levelNum;
    }

    @Column(name = "LEVEL", length = 20)
    public String getLevel() {
        return this.level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    @Column(name = "LEVEL_MAX_NUM")
    public Integer getLevelMaxNum() {
        return this.levelMaxNum;
    }

    public void setLevelMaxNum(Integer levelMaxNum) {
        this.levelMaxNum = levelMaxNum;
    }

    @Column(name = "ACHIVE_NUM")
    public Integer getAchiveNum() {
        return this.achiveNum;
    }

    public void setAchiveNum(Integer achiveNum) {
        this.achiveNum = achiveNum;
    }

    @Column(name = "MATCH_NUM")
    public Integer getMatchNum() {
        return this.matchNum;
    }

    public void setMatchNum(Integer matchNum) {
        this.matchNum = matchNum;
    }

}
