package com.mutuChat.wolfkill.model;

// Generated 2017-4-28 16:49:37 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MutuMemInfo generated by hbm2java
 */
@Entity
@Table(name = "mutu_mem_info")
public class MutuMemInfo implements java.io.Serializable {

    private static final long serialVersionUID = 527438557120360686L;
    private int memId;
    private String memName;
    private String memPhone;

    public MutuMemInfo() {
    }

    public MutuMemInfo(int memId) {
        this.memId = memId;
    }

    public MutuMemInfo(int memId, String memName, String memPhone) {
        this.memId = memId;
        this.memName = memName;
        this.memPhone = memPhone;
    }

    @Id
    @Column(name = "MEM_ID", unique = true, nullable = false)
    public int getMemId() {
        return this.memId;
    }

    public void setMemId(int memId) {
        this.memId = memId;
    }

    @Column(name = "MEM_NAME", length = 30)
    public String getMemName() {
        return this.memName;
    }

    public void setMemName(String memName) {
        this.memName = memName;
    }

    @Column(name = "MEM_PHONE", length = 20)
    public String getMemPhone() {
        return this.memPhone;
    }

    public void setMemPhone(String memPhone) {
        this.memPhone = memPhone;
    }

}
