package com.mutuChat.wolfkill.model;

// Generated 2017-7-26 16:37:38 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

import com.google.gson.annotations.Expose;

/**
 * WolfKillMatchHisDet generated by hbm2java
 */
@Entity
@Table(name = "wolf_kill_match_his_det")
public class WolfKillMatchHisDet implements java.io.Serializable {

    /**
     * 
     * 
     */
    private static final long serialVersionUID = -3467147646827979361L;
    private int id;
    private WolfKillMatchHis wolfKillMatchHis;
    @Expose
    private String playerId;
    @Expose
    private String roleName;
    @Expose
    private Integer winLose;
    @Expose
    private String achiveName;
    @Expose
    private Integer leveladd; 
    @Expose
    private String level;
    @Expose
    private int mvpSign;	

    public WolfKillMatchHisDet() {
    }

    public WolfKillMatchHisDet(int id, WolfKillMatchHis wolfKillMatchHis) {
        this.id = id;
        this.wolfKillMatchHis = wolfKillMatchHis;
    }

    public WolfKillMatchHisDet(int id, WolfKillMatchHis wolfKillMatchHis, String playerId, String roleName,
            Integer winLose, String achiveName) {
        this.id = id;
        this.wolfKillMatchHis = wolfKillMatchHis;
        this.playerId = playerId;
        this.roleName = roleName;
        this.winLose = winLose;
        this.achiveName = achiveName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "MID", nullable = false)
    public WolfKillMatchHis getWolfKillMatchHis() {
        return this.wolfKillMatchHis;
    }

    public void setWolfKillMatchHis(WolfKillMatchHis wolfKillMatchHis) {
        this.wolfKillMatchHis = wolfKillMatchHis;
    }

    @Column(name = "PLAYER_ID", length = 10)
    public String getPlayerId() {
        return this.playerId;
    }

    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }

    @Column(name = "ROLE_NAME", length = 10)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name = "WIN_LOSE")
    public Integer getWinLose() {
        return this.winLose;
    }

    public void setWinLose(Integer winLose) {
        this.winLose = winLose;
    }

    @Column(name = "ACHIVE_NAME", length = 10)
    public String getAchiveName() {
        return this.achiveName;
    }

    public void setAchiveName(String achiveName) {
        this.achiveName = achiveName;
    }
    
    @Column(name = "LEVELADD")
    public Integer getLeveladd() {
		return leveladd;
	}

	public void setLeveladd(Integer leveladd) {
		this.leveladd = leveladd;
	}
	
	@Transient
	public String getLevel() {
        return level;
    }
	@Transient
    public void setLevel(String level) {
        this.level = level;
    }
	
	@Column(name = "MVP_SIGN")
    public int getMvpSign() {
        return mvpSign;
    }
	
    public void setMvpSign(int mvpSign) {
        this.mvpSign = mvpSign;
    }

}
