package com.mutuChat.wolfkill.model;
// Generated 2017-9-1 20:52:59 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WolfKillPregameInfo generated by hbm2java
 */
@Entity
@Table(name = "wolf_kill_pregame_info")
public class WolfKillPregameInfo implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1143280061449839056L;
	private Integer id;
	private String openId;
	private String roomId;
	private Integer seatId;

	public WolfKillPregameInfo() {
	}

	public WolfKillPregameInfo(String openId, String roomId, Integer seatId) {
		this.openId = openId;
		this.roomId = roomId;
		this.seatId = seatId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "OPEN_ID", length = 100)
	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	@Column(name = "ROOM_ID", length = 20)
	public String getRoomId() {
		return this.roomId;
	}

	public void setRoomId(String roomId) {
		this.roomId = roomId;
	}

	@Column(name = "SEAT_ID")
	public Integer getSeatId() {
		return this.seatId;
	}

	public void setSeatId(Integer seatId) {
		this.seatId = seatId;
	}

}
