package com.mutuChat.wolfkill.model;

// Generated 2017-7-26 16:37:38 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import com.google.gson.annotations.Expose;

/**
 * WolfKillMatchHis generated by hbm2java
 */
@Entity
@Table(name = "wolf_kill_match_his")
public class WolfKillMatchHis implements java.io.Serializable {
    
    private static final long serialVersionUID = 8975906196401043198L;
    @Expose
    private int fid;
    @Expose
    private Date matchTime;
    @Expose
    private String matchLog;
    @Expose
    private List<WolfKillMatchHisDet> wolfKillMatchHisDets = new ArrayList<WolfKillMatchHisDet>();

    public WolfKillMatchHis() {
    }

    public WolfKillMatchHis(Date matchTime, String matchLog, List<WolfKillMatchHisDet> wolfKillMatchHisDets) {
        this.matchTime = matchTime;
        this.matchLog = matchLog;
        this.wolfKillMatchHisDets = wolfKillMatchHisDets;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "FID", unique = true, nullable = false)
    public  int getFid() {
        return this.fid;
    }

    public void setFid(int fid) {
        this.fid = fid;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "MATCH_TIME", length = 19)
    public Date getMatchTime() {
        return this.matchTime;
    }

    public void setMatchTime(Date matchTime) {
        this.matchTime = matchTime;
    }

    @Column(name = "MATCH_LOG", length = 1000)
    public String getMatchLog() {
        return this.matchLog;
    }

    public void setMatchLog(String matchLog) {
        this.matchLog = matchLog;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "wolfKillMatchHis")
    @Cascade({ CascadeType.ALL })
    public List<WolfKillMatchHisDet> getWolfKillMatchHisDets() {
        return this.wolfKillMatchHisDets;
    }

    public void setWolfKillMatchHisDets(List<WolfKillMatchHisDet> wolfKillMatchHisDets) {
        this.wolfKillMatchHisDets = wolfKillMatchHisDets;
    }

}
