package com.mutuChat.wolfkill.model;

// Generated 2017-8-1 14:13:45 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WolfKillGoodsInfo generated by hbm2java
 */
@Entity
@Table(name = "wolf_kill_goods_info")
public class WolfKillGoodsInfo implements java.io.Serializable {

    /**
     * serialVersionUID:TODO(描述这个变量用途).
     * 
     */
    private static final long serialVersionUID = -7774758229205501961L;
    private Integer id;
    private String goodsName;
    private String goodsUrl;
    private String goodsDescri;
    private String goodsPrice;

    public WolfKillGoodsInfo() {
    }

    public WolfKillGoodsInfo(String goodsName, String goodsUrl, String goodsDescri, String goodsPrice) {
        this.goodsName = goodsName;
        this.goodsUrl = goodsUrl;
        this.goodsDescri = goodsDescri;
        this.goodsPrice = goodsPrice;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "GOODS_NAME", length = 100)
    public String getGoodsName() {
        return this.goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    @Column(name = "GOODS_URL", length = 100)
    public String getGoodsUrl() {
        return this.goodsUrl;
    }

    public void setGoodsUrl(String goodsUrl) {
        this.goodsUrl = goodsUrl;
    }

    @Column(name = "GOODS_DESCRI", length = 200)
    public String getGoodsDescri() {
        return this.goodsDescri;
    }

    public void setGoodsDescri(String goodsDescri) {
        this.goodsDescri = goodsDescri;
    }

    @Column(name = "GOODS_PRICE", length = 20)
    public String getGoodsPrice() {
        return this.goodsPrice;
    }

    public void setGoodsPrice(String goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

}
