package com.mutuChat.wolfkill.model;
// Generated 2016-10-28 21:40:44 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WolfKillPerInfo generated by hbm2java
 */
@Entity
@Table(name = "wolf_kill_per_info")
public class WolfKillPerInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1679802947969413990L;
	private Integer id;
	private String playerName;
	private String uniqueId;
	private String roleName;
	private Integer totalNum;
	private Integer wonNum;
	private Integer achiveFre;
	private String season;
	private Integer roleTask;
	
    public WolfKillPerInfo() {
	}

	public WolfKillPerInfo(String playerName, String uniqueId) {
		this.playerName = playerName;
		this.uniqueId = uniqueId;
	}

	public WolfKillPerInfo(String playerName, String uniqueId, String roleName, Integer totalNum, Integer wonNum
			,Integer achiveFre,String season,Integer roleTask) {
		this.playerName = playerName;
		this.uniqueId = uniqueId;
		this.roleName = roleName;
		this.totalNum = totalNum;
		this.wonNum = wonNum;
		this.achiveFre = achiveFre;
		this.season = season;
		this.roleTask = roleTask;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PLAYER_NAME", length = 100)
	public String getPlayerName() {
		return this.playerName;
	}

	public void setPlayerName(String playerName) {
		this.playerName = playerName;
	}

	@Column(name = "UNIQUE_ID", nullable = false, length = 20)
	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	@Column(name = "ROLE_NAME", length = 100)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "TOTAL_NUM")
	public Integer getTotalNum() {
		return this.totalNum;
	}

	public void setTotalNum(Integer totalNum) {
		this.totalNum = totalNum;
	}

	@Column(name = "WON_NUM")
	public Integer getWonNum() {
		return this.wonNum;
	}

	public void setWonNum(Integer wonNum) {
		this.wonNum = wonNum;
	}
	@Column(name = "ACHIVE_FRE")
	public Integer getAchiveFre() {
		return this.achiveFre;
	}

	public void setAchiveFre(Integer achiveFre) {
		this.achiveFre = achiveFre;
	}
	
	@Column(name = "SEASON", length = 10)
    public String getSeason() {
        return this.season;
    }

    public void setSeason(String season) {
        this.season = season;
    }
    
    @Column(name = "ROLE_TASK")
    public Integer getRoleTask() {
        return roleTask;
    }

    public void setRoleTask(Integer roleTask) {
        this.roleTask = roleTask;
    }
}
