package com.mutuChat.wolfkill.model;

// Generated 2017-6-28 15:23:52 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WolfKillPerInfoHistory generated by hbm2java
 */
@Entity
@Table(name = "wolf_kill_per_info_history")
public class WolfKillPerInfoHistory implements java.io.Serializable {

    private static final long serialVersionUID = -5494979126875131049L;
    private Integer id;
    private String playerName;
    private String uniqueId;
    private String roleName;
    private Integer totalNum;
    private Integer wonNum;
    private Integer achiveFre;
    private Integer matchNum;

    public WolfKillPerInfoHistory() {
    }

    public WolfKillPerInfoHistory(String playerName, String uniqueId) {
        this.playerName = playerName;
        this.uniqueId = uniqueId;
    }

    public WolfKillPerInfoHistory(String playerName, String uniqueId, String roleName, Integer totalNum,
            Integer wonNum, Integer achiveFre, Integer matchNum) {
        this.playerName = playerName;
        this.uniqueId = uniqueId;
        this.roleName = roleName;
        this.totalNum = totalNum;
        this.wonNum = wonNum;
        this.achiveFre = achiveFre;
        this.matchNum = matchNum;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "PLAYER_NAME", nullable = false, length = 100)
    public String getPlayerName() {
        return this.playerName;
    }

    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    @Column(name = "UNIQUE_ID", nullable = false, length = 20)
    public String getUniqueId() {
        return this.uniqueId;
    }

    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    @Column(name = "ROLE_NAME", length = 100)
    public String getRoleName() {
        return this.roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    @Column(name = "TOTAL_NUM")
    public Integer getTotalNum() {
        return this.totalNum;
    }

    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    @Column(name = "WON_NUM")
    public Integer getWonNum() {
        return this.wonNum;
    }

    public void setWonNum(Integer wonNum) {
        this.wonNum = wonNum;
    }

    @Column(name = "ACHIVE_FRE")
    public Integer getAchiveFre() {
        return this.achiveFre;
    }

    public void setAchiveFre(Integer achiveFre) {
        this.achiveFre = achiveFre;
    }

    @Column(name = "MATCH_NUM")
    public Integer getMatchNum() {
        return this.matchNum;
    }

    public void setMatchNum(Integer matchNum) {
        this.matchNum = matchNum;
    }

}
